markdown: rdiscount
pygments: true
navigation:
  fr:
  - text: Notre Offre
    url: notre-offre.html
    id: menu-item-19
  - text: Solutions
    url: solutions.html
    id: menu-item-18
  - text: Clients et Partenaires
    url: clients-et-partenaires.html
    id: menu-item-17
  - text: La Société
    url: la-societe.html
    id: menu-item-16
  - text: Contact
    url: contact.html
    id: menu-item-15
  en:
  - text: Our Product
    url: our-product.html
    id: menu-item-19
  - text: Solution Profiles
    url: solution-profiles.html
    id: menu-item-18
  - text: Clients and Partners
    url: clients-and-partners.html
    id: menu-item-17
  - text: About Etheryl
    url: about-etheryl.html
    id: menu-item-16
  - text: Contact Us!
    url: contact-us.html
    id: menu-item-15
